FROM cgr.dev/chainguard/wolfi-base:latest

WORKDIR /app

USER root

COPY docker-packages/*.apk packages/
COPY requirements/base.txt requirements-base.txt
COPY prepline_general prepline_general
COPY exploration-notebooks exploration-notebooks
COPY scripts/app-start.sh scripts/app-start.sh
COPY logger_config.yaml logger_config.yaml
COPY CHANGELOG.md CHANGELOG.md

RUN apk update && apk add py3.11-pip mesa-gl glib cmake && \
  apk add --allow-untrusted packages/pandoc-3.1.8-r0.apk && \
  apk add --allow-untrusted packages/poppler-23.09.0-r0.apk && \
  apk add --allow-untrusted packages/leptonica-1.83.0-r0.apk && \
  apk add --allow-untrusted packages/tesseract-5.3.2-r0.apk && \
  apk add --allow-untrusted packages/libreoffice-7.6.5-r0.apk && \
  apk add bash && \
  apk add libmagic && \
  mv /share/tessdata/configs /usr/local/share/tessdata/ && \
  mv /share/tessdata/tessconfigs /usr/local/share/tessdata/ && \
  ln -s /usr/local/lib/libreoffice/program/soffice.bin /usr/local/bin/libreoffice && \
  ln -s /usr/local/lib/libreoffice/program/soffice.bin /usr/local/bin/soffice && \
  chmod +x /usr/local/lib/libreoffice/program/soffice.bin && \
  chmod +x /usr/local/bin/libreoffice && \
  chmod +x /usr/local/bin/soffice

RUN chown -R nonroot:nonroot /app

USER nonroot

RUN pip3.11 install --no-cache -r requirements-base.txt

RUN python3.11 -c "import nltk; nltk.download('punkt')" && \
  python3.11 -c "import nltk; nltk.download('averaged_perceptron_tagger')" && \
  python3.11 -c "from unstructured.partition.model_init import initialize; initialize()" && \
  python3.11 -c "from unstructured_inference.models.tables import UnstructuredTableTransformerModel; model = UnstructuredTableTransformerModel(); model.initialize('microsoft/table-transformer-structure-recognition')"

ENV PATH="${PATH}:/home/nonroot/.local/bin"
ENV TESSDATA_PREFIX=/usr/local/share/tessdata

ENTRYPOINT ["scripts/app-start.sh"]
# Expose a default port of 8000. Note: The EXPOSE instruction does not actually publish the port,
# but some tooling will inspect containers and perform work contingent on networking support declared.
EXPOSE 8000