{{- if and .Values.apiKey.enabled (not .Values.apiKey.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unstructured-api.apiKeySecretName" . }}
  labels:
    {{- include "unstructured-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  UNSTRUCTURED_API_KEY: {{ .Values.apiKey.value | quote }}
{{- end }}
